server:
  port: 8081

spring:
  profiles:
    active: local, mysql

datasource:
  mysql:
    jdbcUrl: jdbc:mysql://localhost:3306/user
    driverClassName: com.mysql.cj.jdbc.Driver
    userName: root
    password: Abhi@2109

---
spring:
  profiles:
    configure:
      on-activate: dev

datasource:
  mysql:
    jdbcUrl:
    driverClassName:
    username:
    password:

---
spring:
  profiles:
    configure:
      on-activate: stage

datasource:
  mysql:
    jdbcUrl:
    driverClassName:
    username:
    password:

---
spring:
  profiles:
    configure:
      on-activate: prod